// <auto-generated />

namespace Yousource.Api.Messages.Orders.Requests
{
    using System.ComponentModel.DataAnnotations;
    using Newtonsoft.Json;

    public class AddOrderWebRequest : WebRequest
    {
        [JsonProperty("customerName")]
        [Required]
        public string CustomerName { get; set; }

        [JsonProperty("customerEmail")]
        [Required]
        public string CustomerEmail { get; set; }

        [JsonProperty("recipientName")]
        [Required]
        public string RecipientName { get; set; }

        [JsonProperty("recipientEmail")]
        [Required]
        public string RecipientEmail { get; set; }

        [JsonProperty("storeName")]
        [Required]
        public string StoreName { get; set; }

        [JsonProperty("voucherPrice")]
        [Required]
        public float VoucherPrice { get; set; }

        [JsonProperty("dedication")]
        public string Dedication { get; set; }

        [JsonProperty("orderDate")]
        public string OrderDate { get; set; }
    }
}
