// <auto-generated />

namespace Yousource.Services.Order
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Yousource.Infrastructure.Interfaces;
    using Yousource.Infrastructure.Logging;
    using Yousource.Infrastructure.Messages.Orders.Requests;
    using Yousource.Infrastructure.Messages.Orders.Responses;
    using Yousource.Services.Order.Constants;
    using Yousource.Services.Order.Data;
    using Yousource.Services.Order.Exceptions;
    using Yousource.Services.Order.Extensions;
    using Yousource.Services.Order.Specifications;

    //// Service typically executes the operations needed e.g. CRUD.
    public class OrderService : IOrderService
    {
        private readonly IOrderDataGateway dataGateway;
        private readonly ILogger logger;

        //// Inject dependencies. Usually data access dependencies i.e. Data Gateways
        public OrderService(
            IOrderDataGateway dataGateway,
            ILogger logger)
        {
            this.dataGateway = dataGateway;
            this.logger = logger;
        }

        public async Task<CreateOrderResponse> CreateOrderAsync(CreateOrderRequest request)
        {
            var result = new CreateOrderResponse();
            var errors = Enumerable.Empty<string>() as ICollection<string>;

            try
            {
                //// Validate using Specification classes. You can leverage factories to inject
                //// your specifications if it touches the database
                var spec = new ValidCreateOrderRequestSpecification();
                if (spec.IsSatisfiedBy(request, ref errors))
                {
                    //// Decouple Service Models from Shared models i.e. Create `AsEntity` extension to convert vice-versa
                    await this.dataGateway.InsertOrderAsync(request.AsEntity());
                }
                else
                {
                    //// Communicate Specification-added errors, and return appropriate error.
                    result.SetError(Errors.CreateValidationError, errors);
                }
            }
            catch (Exception ex)
            {
                //// Log and Wrap exception then rethrow
                this.logger.WriteException(ex);
                throw new OrderServiceException(ex);
            }

            return result;
        }

        public async Task<GetOrdersResponse> GetOrdersAsync()
        {
            var result = new GetOrdersResponse();
            try
            {
                //// Convert Entity (Service) model to Shared (Infra) model using `AsModel` extension
                result.Data = (await this.dataGateway.GetOrdersAsync()).AsModel();
            }
            catch (Exception ex)
            {
                //// Wrap exception and rethrow
                this.logger.WriteException(ex);
                throw new OrderServiceException(ex);
            }

            return result;
        }
    }
}
