// <auto-generated />

namespace Yousource.Services.Order.Data
{
    using System.Data.SqlClient;
    using Yousource.Services.Order.Data.Entities;

    public interface IOrderSqlCommandFactory
    {
        SqlCommand CreateInsertOrderCommand(OrderEntity order);

        SqlCommand CreateGetOrdersCommand();

    }
}
