// <auto-generated />

namespace Yousource.Api.Controllers
{
    using System.Diagnostics;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Yousource.Api.Extensions;
    using Yousource.Api.Extensions.Order;
    using Yousource.Api.Filters;
    using Yousource.Infrastructure.Interfaces;

    //// Use the Page Controllers or Experience Controllers convention wherein
    //// we create controllers per "pages/experience" and not in a RESTful manner
    [Route("api/orders")]
    public class OrdersController : ControllerBase
    {
        private readonly IOrderService service;

        //// Inject controller dependencies. Usually services
        public OrdersController(IOrderService service)
        {
            Debug.Assert(service != null, "Null dependencies");
            this.service = service;
        }

        [HttpGet]
        [AllowAnonymous]
        [ServiceFilter(typeof(ValidateModelStateAttribute))]
        [ServiceFilter(typeof(LogExceptionAttribute))]
        //// Controller code should only contain two lines i.e. invocation of service
        public async Task<IActionResult> GetOrdersAsync()
        {
            var result = await this.service.GetOrdersAsync();
            return this.CreateResponse(result.AsWebResponse());
        }

    }
}
