// <auto-generated />

namespace Yousource.Services.Order.Extensions
{
    using System.Collections.Generic;
    using System.Linq;
    using Yousource.Infrastructure.Messages.Orders.Requests;
    using Yousource.Infrastructure.Models.Orders;
    using Yousource.Services.Order.Data.Entities;

    public static class OrderExtensions
    {
        public static OrderEntity AsEntity(this CreateOrderRequest request)
        {
            var result = new OrderEntity
            {
                Dedication = request.Dedication,
                VoucherPrice = request.VoucherPrice,
                StoreName = request.StoreName,
                RecipientEmail = request.RecipientEmail,
                RecipientName = request.RecipientName,
                CustomerEmail = request.CustomerEmail,
                CustomerName = request.CustomerName
                //// Assign all necessary fields e.g. when new fields are introduced
            };

            return result;
        }

        public static IEnumerable<Order> AsModel(this IEnumerable<OrderEntity> entities)
        {
            var result = entities.Select(entity => entity.AsModel());
            return result;
        }

        public static Order AsModel(this OrderEntity entity)
        {
            var result = new Order
            {
                OrderDate = entity.OrderDate,
                Dedication = entity.Dedication,
                VoucherPrice = entity.VoucherPrice,
                StoreName = entity.StoreName,
                RecipientEmail = entity.RecipientEmail,
                RecipientName = entity.RecipientName,
                CustomerEmail = entity.CustomerEmail,
                CustomerName = entity.CustomerName,
                OrderID = entity.OrderID
                //// Assign all necessary fields e.g. when new fields are introduced
            };

            return result;
        }
    }
}
