// <auto-generated />

namespace Yousource.Api.Extensions.Injection
{
    using Microsoft.Extensions.Configuration;
    using Microsoft.Extensions.DependencyInjection;
    using Yousource.Infrastructure.Interfaces;
    using Yousource.Services.Order;
    using Yousource.Services.Order.Data;

    public static class OrderServices
    {
        public static void InjectOrderService(this IServiceCollection services, IConfiguration configuration)
        {
            services.AddSingleton<IOrderService, OrderService>();
            services.AddSingleton<IOrderSqlCommandFactory, OrderSqlCommandFactory>();
            services.AddSingleton<IOrderDataGateway, OrderSqlDataGateway>();
        }
    }
}
